### ISSUE TITLE
Maybe publish a NPM package for project? 

### ISSUE THREAD

**Issue by malsabbagh** [ExtendScript/CSInterface#2]
@MrSpoocy It would be nice to have this as a NPM package.  I know you did request to merge with https://github.com/BrightShadow/CSInterface-TS

@BrightShadow is too busy and it will be nice to have v9 and even v10 support published as an TS ready NPM.

**Comment by MrSpoocy** [comment]
@ff6347 Can you please create a secret for npm and add it to the GitHub Settings? That I can try to push it at @extendscript/csinterface ?

**Comment by ff6347** [comment]
@MrSpoocy I added a org secret `NPM_TOKEN` with access to npms scope `@extendscript`

**Comment by MrSpoocy** [comment]
@malsabbagh Sorry, for the really really late answer, we published a NPM package now. Currently it holds only <= v9, but v10 & v11 will follow soon
